### ISSUE TITLE
Compositor is not fullscreen

### ISSUE THREAD

**Issue by deadwood-pl** [ValveSoftware/SteamVR-for-Linux#104]
#### Your system information
* Steam client version (build number or date): 1524242469
* Distribution (e.g. Ubuntu): Linux Mint 18.3
* Graphics driver version (run nvidia-settings): 390.48
* Gist for SteamVR System Information:  https://gist.github.com/deadwood-pl/95f0e6c0bc3601f774f5ace9d5268947
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I'm trying to get Vive working under Linux Mint 18.3 and I'm having issues. When using non-Beta Steam client and Steam VR I was getting 306 and 307 errors. Once I moved to beta Steam and Steam VR I get the 306 error popup but vrmonitor says that Compositor needs to be made fullscreen (-202).

GFX Card: GFX 1060 3GB

![ss](https://user-images.githubusercontent.com/12008201/39274740-40b8dbba-48e3-11e8-9144-30a82f6e5e74.jpg)

#### Steps for reproducing this issue:
1. Plugin HMD + one base station set to A
2. Start Steam
3. Start SteamVR
4. Get error

**Comment by deadwood-pl** [comment]
Hello @kisak-valve ,

In the `/usr/share/vulkan/icd.d/ directory` I only have the `nvidia_icd.json`.

I modified it as explained [here](https://askubuntu.com/questions/967335/vulkan-does-not-work/967910#967910)
```

{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.0.65"
    }
}
```

I'm attaching the output of vulkaninfo: 
[vulkaninfo.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/1949822/vulkaninfo.txt)

PS. If needed I'm able to debug code in gdb/assembler.

**Comment by deadwood-pl** [comment]
Is there any more debug I can enable somewhere to get more details of this problem?

**Comment by deadwood-pl** [comment]
Hi,

Indeed vrcompository is "zombied" (<defunc>). I was able to get debug by running vrmonitor from console. Seems some core dumps are generated as well. I'm attaching the console output:

[out.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/1971855/out.txt)

One thing that is interesting is this portion of output:

```
output 0x1be 10 modes
	mode 0 0x1bf 1680x1050 (looking for 2160x1200)
	mode 1 0x1c0 1280x1024 (looking for 2160x1200)
	mode 2 0x1c1 1280x1024 (looking for 2160x1200)
	mode 3 0x1c2 1152x864 (looking for 2160x1200)
	mode 4 0x1c3 1024x768 (looking for 2160x1200)
	mode 5 0x1c4 1024x768 (looking for 2160x1200)
	mode 6 0x1c5 800x600 (looking for 2160x1200)
	mode 7 0x1c6 800x600 (looking for 2160x1200)
	mode 8 0x1c7 640x480 (looking for 2160x1200)
	mode 9 0x1c8 640x480 (looking for 2160x1200)
output 0x1c9 0 modes
output 0x1ca 0 modes
output 0x1cb 0 modes
output 0x1cc 0 modes
output 0x1cd 0 modes
output 0x1ce 0 modes
output 0x1cf 0 modes
output 0x0
```
Software seems to be looking for Vive resolution on my main monitor?

**Comment by deadwood-pl** [comment]
I have additional question: should Vive be visible as a "monitor" (separate Screen) in nvidia settings?

Currently only my main monitor is visible there. The monitor is connected via DVI-D, Vive via HDI. The monitor is not FullHD capable (if that makes any difference)

**Comment by kisak-valve** [comment]
Since the [nvidia 378.xx](http://us.download.nvidia.com/XFree86/Linux-x86/378.09/README/xconfigoptions.html) series proprietary driver, the driver has required the "AllowHMD" X config setting to be used if you want to extend your desktop onto a Vive.

Just a guess here, but it may be worth double checking the connections on the HMD side of the cable.

**Comment by deadwood-pl** [comment]
Thanks - after using that option the Vive is detected and I can enable extending Screen 0 to it. It also displays the image - so the hardware part of the setup seems to be working correctly.

**Comment by deadwood-pl** [comment]
Additionally this seems to move things a bit forward. Now, with Vive visible in nvidia settings but still disabled, I no longer get 306/307 errors and the logs show that required resolution is found on Vive. The compositor is not full screen error still is there though.

**Comment by ishiguroJSK** [comment]
I encountered same problem recently (2018/05) , and I managed to solve it on my PC.
A while ago, I could run SteamVR with no problem at Ubuntu14.04 QuadroM4000M, driver 387.12, vulkan 1.1.70, direct-mode.
Since latest steam update, the error occured and I tried to catch up latest requirement.
As you can see in 
https://github.com/moon-wreckers/vive_tracker
they install latest vulkan from the site.
https://vulkan.lunarg.com/sdk/home#linux
and I edited /usr/share/vulkan/nvidia_icd.json as
```
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.1.73"
    }
}
```
With this method, I could solve my problem at Ubuntu14.04 QuadroM4000M, driver 396.24, vulkan(1.1.73), direct-mode.
(However with my another PC at Ubuntu14.04 QuadroK2100M, driver 396.24, vulkan 1.1.73,
the direct-mode doesn't work and SteamVR doesn't work yet.)

**Comment by deadwood-pl** [comment]
I'm starting to think that somehow my whole setup is broken. Can someone confirm that if I:

1) Download Steam
2) Download SteamVR [beta]
3) Do not connect any Vive hardware
4) Select NULL driver in steamvr config file
5) Run SteamVR Tutorial

SteamVT Tutorial should run and I should be able to see the rendering (images for both eyes?) of SteamVR Tutorial as a window on Linux desktop?

**Comment by deadwood-pl** [comment]
Heh, I think I managed to get to the bottom of the problem. To do this I ran manually vrserver and then vrcompositor under gdb. The effect is:

```
Thread 11 "RenderThread" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffc8ec0700 (LWP 27976)]
0x0000000000432674 in CGenericResources::Update(vr::IGraphicsDevice::UpdateParams_t const&) ()
(gdb) bt
#0  0x0000000000432674 in CGenericResources::Update(vr::IGraphicsDevice::UpdateParams_t const&) ()
#1  0x000000000041b35f in vr::CHmdDistort::Update(vr::EVREye, vr::CHmdDistort::UpdateParams_t const*, vr::TrackedDevicePose_t const*, vr::ETrackingUniverseOrigin, unsigned long) ()
#2  0x0000000000455c6b in CRenderThread::Update() ()
#3  0x000000000045790d in CRenderThread::Run() ()
#4  0x00000000004f97d0 in SteamThreadTools::CThread::ThreadProc(void*) ()
#5  0x00007ffff5a8a6ba in start_thread (arg=0x7fffc8ec0700) at pthread_create.c:333
#6  0x00007ffff57c041d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

And the problem code is:

```
   0x000000000043265a <+24906>:	movaps 0x178f1f(%rip),%xmm3        # 0x5ab580
   0x0000000000432661 <+24913>:	shufps $0x6c,%xmm1,%xmm1
   0x0000000000432665 <+24917>:	movdqa %xmm1,%xmm2
---Type <return> to continue, or q <return> to quit---
   0x0000000000432669 <+24921>:	mov    %rax,-0x970(%rbp)
   0x0000000000432670 <+24928>:	shufps $0x6c,%xmm0,%xmm0
=> 0x0000000000432674 <+24932>:	palignr $0xc,%xmm0,%xmm2
   0x000000000043267a <+24938>:	lea    -0x6a0(%rbp),%rax
   0x0000000000432681 <+24945>:	shufps $0x6c,%xmm3,%xmm3
```

It seems that the vrcompositor is compiled with flags allowing usage of SSSE3 instructions which my Phenom II doesn't implement.

Is this by mistake or by design? (what is the minimal required CPU for SteamVR then?)
