### ISSUE TITLE
BUG] SteamVR failed to initialize for unkown reasons. (Error: Installation Not Found (100) (100))

### ISSUE THREAD

**Issue by jeisom** [ValveSoftware/SteamVR-for-Linux#702]
**Describe the bug**
I get the above error launching SteamVR and home never loads.  SteamVR itself works, dashboard ,  and I have used Assetto Corsa Competizione and Dirt Rally 2.0.   

1. Launch SteamVR
2. See error

**Expected behavior**

**System Information (please complete the following information):**
Please use the latest Steam beta client and SteamVR beta for your bug reports!

* Steam client version (build number or date): 2024/05/14
* SteamVR version: 2.5.5
* Distribution (e.g. Ubuntu): Arch Linux
* Steam runtime diagnostics:  
[steam-runtime-log-2024-05-14.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/15312286/steam-runtime-log-2024-05-14.txt)

* Steam and SteamVR logs:  [steam-logs.tar.gz](https://github.com/ValveSoftware/SteamVR-for-Linux/files/15312278/steam-logs.tar.gz)]
* Minidumps: [steam-minidumps.tar.gz](https://github.com/ValveSoftware/SteamVR-for-Linux/files/15312308/steam-minidumps.tar.gz)
**Screenshots**
![Screenshot_20240514_130120](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/30381174/61af08bf-8693-42a7-bacc-875d6fab2d79)

It used to work in the past, but it probably has been a while as I had not used the headset for several months.  Running Nvidia driver on Plasma 6 wayland.

**Comment by Fairlightish** [comment]
Having the same issue on SteamVR 2.5.5 and 2.6.1 beta.
Ubuntu, KDE Plasma, X11

**Comment by mikeyjoel** [comment]
Make sure to right-click SteamVR -> Properties > Betas > Beta Participation and select previous - The previous release.

While that updates, go to your ProtonUp-QT (If you don't have it, install it from flathub) and go to About and check mark Enable advanced mode. Click add version and install Steam-Non-Play.

Quit Steam. Relaunch and start the SteamVR[previous], which will run some internal scripts (located at `~/.local/steam/bin/steam-runtime/run.sh /home/linux/.local/share/Steam/steamapps/common/SteamVR/bin/vrsetup.sh`)

Make sure you are using Wayland, just X11.

And you should be good to go. If not try running the vrsetup.sh script and post the error output. Most of the time, folks are missing getcap/setcap package.

**Comment by jeisom** [comment]
> Make sure to right-click SteamVR -> Properties > Betas > Beta Participation and select previous - The previous release.
> 
> While that updates, go to your ProtonUp-QT (If you don't have it, install it from flathub) and go to About and check mark Enable advanced mode. Click add version and install Steam-Non-Play.

I assume Steam-Play-none.  I didn't see Steam-non-play.
 
> Quit Steam. Relaunch and start the SteamVR[previous], which will run some internal scripts (located at `~/.local/steam/bin/steam-runtime/run.sh /home/linux/.local/share/Steam/steamapps/common/SteamVR/bin/vrsetup.sh`)

I feel like this is supposed to trigger something happening, but I don't notice any difference.

> Make sure you are using Wayland, just X11.

??  Not sure what you are trying to communicate, but both wayland and X11 work equally for me.
 
> And you should be good to go. If not try running the vrsetup.sh script and post the error output. Most of the time, folks are missing getcap/setcap package.

Those are installed.

vrsetup.sh[51001]: exec /home/jeisom/.local/share/Steam/steamapps/common/SteamVR/bin/vrenv.sh /home/jeisom/.local/share/Steam/steamapps/common/SteamVR/bin/vrsetup.sh
vrenv.sh[51001]: VRCOMPOSITOR_LD_LIBRARY_PATH=/home/jeisom:/home/jeisom/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/jeisom/.local/share/Steam/steamapps/common/SteamVR/bin/linux64
vrenv.sh[51001]: exec /home/jeisom/.local/share/Steam/steamapps/common/SteamVR/bin/vrsetup.sh
vrsetup.sh[51001]: Relaunching under scout LDLP runtime.
vrsetup.sh[51001]: exec /home/jeisom/.steam/bin/steam-runtime/run.sh /home/jeisom/.local/share/Steam/steamapps/common/SteamVR/bin/vrsetup.sh
vrsetup.sh[51001]: Detected scout LDLP runtime.
vrsetup.sh[51001]: /home/jeisom/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher binary has cap_sys_nice privileges


I still get the error and SteamVR Home doesn't load.  SteamVR itself works, I get the vr enviroment with the background and can bring up the dashboard and I have successfully run games.  My camera even works.

**Comment by mikeyjoel** [comment]
https://en.opensuse.org/Steam#Failure_to_start_Steam,_when_trying_to_load_Steam_without_local_runtime

Can you check if you are part of the video, audio, and games group ? That's for SUSE but applies to all distros as well. Trying to make sure you have access to 32-bit libraries as well. Should be home to test on my arch workstation tonight. Mobile at the moment.

Also, reason why I brought up the X11/Wayland topic is because I personally had issues launching games like Moss on Wayland, had to switch to X11.

**Comment by jeisom** [comment]
It looks like everything is accounted for for lib32.  I believe steamtours is the "home" app and I tried running it from bash and in gdb I get(using a 5900x):

Thread 1 "steamtours" received signal SIGSEGV, Segmentation fault.
__strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:67
67              vmovdqu (%rdi), %ymm2
(gdb) where
#0  __strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:67
#1  0x00007fffd476f895 in ?? () from /home/jeisom/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libpanorama.so
#2  0x00007fffffff9350 in ?? ()
#3  0x0000000000000004 in ?? ()
#4  0x000055555748abe0 in ?? ()
#5  0x00000000e523b830 in ?? ()
#6  0x3030303030303330 in ?? ()
#7  0x3030303034306436 in ?? ()
#8  0x3030303032636536 in ?? ()
#9  0x3030303031303131 in ?? ()
#10 0x00007fffffff9300 in ?? ()
#11 0x00007fffffff93b0 in ?? ()
#12 0x00007fffffff9440 in ?? ()
#13 0x00007fffffff93a0 in ?? ()
#14 0x0000000000000001 in ?? ()
#15 0x00007fffe522fab6 in ?? () from /home/jeisom/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libpanorama_text_pango.so
#16 0x00007fffffff9390 in ?? ()
#17 0x00007fffe53ae659 in ?? () from /home/jeisom/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libpanorama_text_pango.so
#18 0x0000555576aa08c0 in ?? ()
#19 0x000000000000006e in ?? ()
#20 0x0000555576bf5990 in ?? ()
#21 0x0000555576d7c600 in ?? ()
#22 0x000000010000001f in ?? ()
#23 0x0000000000000000 in ?? ()
