### ISSUE TITLE
OpenGL clients segfault

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#97]
#### Your system information
* Steam client version (build number or date):  ![screenshot_20180306_213103](https://user-images.githubusercontent.com/781076/37056796-b3ea454a-2185-11e8-9ea7-3c72b51a0830.png)
* Distribution (e.g. Ubuntu): Archlinux
* Graphics driver version (run nvidia-settings): radv git 322a51b549
* Gist for SteamVR System Information: [steamvrsystemreport.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/1786616/steamvrsystemreport.txt)
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes

Happens immediately on startup
```
Thread 1 "hellovr_opengl" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fffe827a2fe in CSharedBufferLinux::CreateVulkanBufferForExport(void*, void*, unsigned long, unsigned int, bool) ()
   from /home/chris/.local/share/Steam/SteamApps/common/SteamVR/bin/linux64/vrclient.so
#2  0x00007fffe8176d6c in CVRCompositorSharedTextures::UpdateTextureSet(CVRCompositorSharedTextures::Params const*, VRCompositorState_TextureSet_t*) ()
   from /home/chris/.local/share/Steam/SteamApps/common/SteamVR/bin/linux64/vrclient.so
#3  0x00007fffe816eb65 in CVRCompositorClient::Submit(vr::EVREye, vr::Texture_t const*, vr::VRTextureBounds_t const*, vr::EVRSubmitFlags) ()
   from /home/chris/.local/share/Steam/SteamApps/common/SteamVR/bin/linux64/vrclient.so
#4  0x00005555555755ca in CMainApplication::RenderFrame() ()
#5  0x0000555555576302 in CMainApplication::RunMainLoop() ()
#6  0x000055555555d557 in main ()
```

**Comment by lostgoat** [comment]
@ChristophHaag got this repro'd locally, seems like a radv regression. 

I'll narrow the details tomorrow morning.
